### ISSUE TITLE
can not set up cog and pfam database right

### ISSUE THREAD

**Issue by wanjinhu** [metagenlab/zDB#129]
Hi

When I setup zdb database, kegg, vfdb and swissprot can set up successfully, but can not set up cog and pfam database right. here is the  log file [nextflow.log](https://github.com/user-attachments/files/16991475/nextflow.log)

I know it is not zdb issue, maybe you can upload the database somewhere and let us download it and put it in the corresponding folder?

Thanks

Wanjin Hu

**Comment by njohner** [comment]
I'll close this issue for inactivity.
