### ISSUE TITLE
Cant download any of the faa/fna/ffn/gbk file from the genome page when --docker is used

### ISSUE THREAD

**Issue by TKlamydionaut** [metagenlab/zDB#15]
Seems like the part that binds the results and assets folders together does not happen.
bind_path_results+=("${dir}/zdb/results/blast_DB/${run_name}":"${zdb_folder}/assets/blast_DB/${run_name}")

Also, the path for the gbk file download should be  RunName/gbk/filtered instead of just RunName/gbk

**Comment by bkm** [comment]
Hello (Thomas, I guess?),

Does the blast interface work in dockers ?
I'll check into the genome files download.

Thanks for bringing this up.
Bastian

**Comment by TKlamydionaut** [comment]
Hello Bastian !


Oui j''arrive a blaster avec Docker 😊          Si je repere d'autres problemes je les submitterais !



________________________________
De : bkm ***@***.***>
Envoyé : mardi, 4 juillet 2023 05:50:30
À : metagenlab/zDB
Cc : Kozusnik Thomas; Author
Objet : Re: [metagenlab/zDB] Cant download any of the faa/fna/ffn/gbk file from the genome page when --docker is used (Issue #15)


Hello (Thomas, I guess?),

Does the blast interface work in dockers ?
I'll check into the genome files download.

Thanks for bringing this up.
Bastian

**Comment by tpillone** [comment]
Hello, 
Some files from the asset folder cannot be accessed when using docker because they are symlinks to the work directory (e.g faa and fna from the "genome" page). Blast indexes are not symblinks and can be accessed without problems.
We could fix this by simply moving files to the result folder instead of making symlinks.

**Comment by bkm** [comment]
This should fix it. @tpillone  could you take a look at the PR ? If it's alright, I'll create a conda package tonight.

**Comment by tpillone** [comment]
It looks good!
