### ISSUE TITLE
ORGANISM tag in GBK input & conda

### ISSUE THREAD

**Issue by GeoMicroSoares** [metagenlab/zDB#18]
Hi @cbertell @bkm - thanks for developing this tool - it seems great! I'm giving it a try on some of my MAGs and was confronted with the fact that my prodigal-generated GBK files were apparently incomplete. After correcting this using pyrodigal, I was then confronted with the lack of an ORGANISM field, which isn't relevant in my case. I wrote a python script to quickly go around this, but then was left wondering if it wouldn't be possible to remove this requirement and accept 'incomplete' prodigal-generated GBK input? I think this is a golden-standard tool used by a significant fraction of the metagenomics community for example, which will benefit from this tool.
Additionally, I noticed zDB uses conda to generate its environments during the NextFlow run - maybe using mamba could improve the run time of the tool?
Hope this is relevant & helps you! Thanks in advance!

**Comment by GeoMicroSoares** [comment]
Quick follow-up on this as it's conda-related - I can't run the webapp command as it can't create the conda environment. Could you look into this as well please?
```
$ zdb webapp --conda --name=MG1_zdb_270923
Building conda environment...
Failed to build conda environment, you can check conda_log for details
```

**Comment by GeoMicroSoares** [comment]
Just taking time to try out a couple different things - all works for me if I change `conda` to `mamba` in `[this line](https://github.com/metagenlab/zDB/blob/d9069abbc92e60236a5fbe645ed1030ca6eaab2c/bin/zdb#L354)` (having already installed mamba in the zdb environment...

**Comment by tpillone** [comment]
Hi @GeoMicroSoares 

The gbk field `ORGANISM` is not required if you add a column `name` in the sample file to label your input files.
  
Prodigal gbk outputs do not contain any sequences, which is the main reason why we cannot use them as input for zDB. It would probably be possible to take the original fasta file + the prodigal gbk file as input. We could also provide a script to generate complete gbk records from incomplete prodigal outputs.

We are aware of the fact that some environments are difficult to install with conda, this is one of the the reasons why we recommend using docker or singularity. Switching to mamba is probably a good idea.

Thank you for your feedback!

**Comment by njohner** [comment]
I'm closing this issue as it is really old and you seemed OK with the answer given.
