### ISSUE TITLE
Plot region optimization 

### ISSUE THREAD

**Issue by TKlamydionaut** [metagenlab/zDB#55]
Hi ! 

Do you think there is a possiblity to choose the order in which the genomic regions are plotted ? Like for example in the order in which they are selected ? 

In the screenshot below, you can see that there are 2 different possible orientation in the genomes of the gene of interest. However the regions are not clustered together in the plot, leading to this confusing graph. 

![e918ec5c-2849-44ac-a736-d1f280504af3](https://github.com/metagenlab/zDB/assets/119929162/64f3c73c-6ec7-44e9-8c35-1f131b9365d6)

All the best !

**Comment by bkm** [comment]
Hello,
Yes, this is something that is planned : either by letting the user choose the order of the loci or by following the same order as in the phylogenetic tree.

**Comment by bkm** [comment]
I'll see if I can squeeze some time to implement those in the upcoming weeks.

**Comment by njohner** [comment]
I've added an automatic optimization of the representation order.
resolved by #137
