### ISSUE TITLE
Conda env issues

### ISSUE THREAD

**Issue by rubenluz** [metagenlab/zDB#91]
Hello,

1.
The Biopython version has to be fixed at 1.81 in webapp.yaml
`from Bio.SeqUtils import GC which is a function deprecated in Biopython 1.80 and removed in Biopython 1.82.`

2.
"0.0.0.0" is not authorized local host, so it raises problems it can be solved by adding it, but something explaining how could be nice.

SUGESTION:

Could the program be adaptet to accept gff3 from bakta (modern substitute for Prokka!!)

Thanks

**Comment by njohner** [comment]
Hi thanks for the feedback.
1. It should normally run with biopython versions newer than 1.82, I've fixed that issue some time ago. See https://github.com/metagenlab/zDB/pull/34, but it's not released yet. So you might have issues depending on how you installed, are running things (containers are very outdated compared to source code). Did you install from source? With conda? What command were your running when you got that error?
2. Are you running on MacOs? If so, this is already documented in the README (see https://github.com/metagenlab/zDB?tab=readme-ov-file#starting-the-web-server).

I'll be making a new release this week, with a lot of new features. This should also help with installing and running the software as containers will be up to date with source code again.

As for your suggestion, we were discussion of integrating bakta to allow doing the annotations directly with zdb. I could also have a look at supporting other input file formats. Of course we are also open to PRs.

**Comment by njohner** [comment]
Ok I'll close this issue. The new release has been out for some time now, you can install it with conda, containers are up to date so the issue reported above should not exist anymore.
